;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname declaration) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
;; CS 145 Midterm Request Form
;;
;; Please fill in your Marmoset ID and your name, immediately
;; after the colon (:) where requested and submit to Marmoset
;; By submititing this file to Marmoset as project M1Request
;; you declare that the statements below accurate, and that you will
;; be bound by their terms.

;; Do not edit this file other than to fill in the required
;; information

;; This file must be named declaration.rkt when submitted

(define declaration "
    My Marmoset login ID is:lrwatson

    I declare that I am authorized to use this Marmoset login,
    and that I have not given and will not give anyone else
    other than cs145 instructional staff access to Marmoset using
    this login.

    I understand that when I submit this file Marmoset will
    give me access to an exam in the form of a Racket file that
    I will download, fill out, and submit to Marmoset within two
    hours (120 minutes) of submitting this request.

    I understand that I may submit the exam to Marmoset as many
    times as I wish, but only the last submission prior to the 120
    minute deadline will be marked.

    I understand that I must use my own Marmoset account, and that
    it would be an academic offense to submit the exam or any portion
    of the exam using a different Marmoset account.

    I understand that it would be an academic offense to submit any
    material received from any other individual or any other source,
    whether it be an exam, solution, or any other material.

    I understand that it would be an academic offense to share any
    information about this exam with anyone else, or to accept or
    to solicit help from anyone else.  Your responses to the exam
    must be your own work.

    I understand that I may consult DrRacket documentation but no
    other sources.

    I understand that this request and the exam may be run using
    DrRacket, and that if I fill them out as required they will
    run without error, but may not produce meaningful output.

    My Name is:Liam Watson
")

    